### ISSUE TITLE
duplicate constraint errors when loading assets.sql twice

### ISSUE THREAD

**Issue by ajh** [forgottentea/pg_assets#4]
1. create a new rails database but don't load the assets file
2. load assets file with `rake pg:assets:load`
3. load assets file again with `rake pg:assets:load`

expected: The second rake task to succeed, and not really change anything
actual: get errors like:

```
PG::DuplicateObject: ERROR:  constraint "foos_bars_fk" for relation "foos" already exists
```

Seems like it'd be good for the assets.sql file to be idempotent.

**Comment by ajh** [comment]
I was working on a fix for this here, but didn't finish it: https://github.com/ajh/pg_assets/commit/4f218cd4340c7cd870a6d9973b5dbfb74ea27673

**Comment by forgottentea** [comment]
I like this idea... simple:  http://stackoverflow.com/a/25403384

**Comment by ajh** [comment]
Which one, this?

```
ALTER TABLE foo DROP CONSTRAINT IF EXISTS bar;
ALTER TABLE foo ADD CONSTRAINT bar ...;
```

See the rebutal to that in the accepted answer:

> That's probably fine in your development database, or where you know you can shut out the apps that depend on this database for a maintenance window.

> But if this is a lively mission critical 24x7 production environment you don't really want to be dropping constraints willy nilly like this. Even for a few milliseconds there's a short window where you're no longer enforcing your constraint which may allow errant values to slip through. That may have unintended consequences leading to considerable business costs at some point down the road.

Also I don't know if a constraint would ever be expensive to drop and create. Something else to consider.

**Comment by forgottentea** [comment]
Yeah I saw that.  The whole pg:assets:load is wrapped in a transaction, so I wouldn't worry about that.

Also for constraints..  I don't think they are expensive.  There are some issues around creating constraints when data is bad (thus invalidating the constraint with existing data), but I think that is out of scope for this gem..  maybe we could provide a helper though.  

Indexes are another story though.

**Comment by forgottentea** [comment]
Fixing this and a related materialized view issue here: https://github.com/forgottentea/pg_assets/tree/Make-pg-assets-load-non-destructive-when-run-multiple-times
